name: lab_7_415916_test

on:
  push:
    branches:
      - roboczy

jobs:
  test_dodawanie:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r ./Lab_7/env_415916/requirements.txt

      - name: Run test_dodawanie
        run: |
          cd ./Lab_7/env_415916 && pytest calculator_test.py::test_dodawanie

  test_odejmowanie:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r ./Lab_7/env_415916/requirements.txt

      - name: Run test_odejmowanie
        run: |
          cd ./Lab_7/env_415916 && pytest calculator_test.py::test_odejmowanie

  test_mnozenie:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r ./Lab_7/env_415916/requirements.txt

      - name: Run test_mnozenie
        run: |
          cd ./Lab_7/env_415916 && pytest calculator_test.py::test_mnozenie

  test_dzielenie:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r ./Lab_7/env_415916/requirements.txt

      - name: Run test_dzielenie
        run: |
          cd ./Lab_7/env_415916 && pytest calculator_test.py::test_dzielenie

  new_test:
    runs-on: ubuntu-latest
    needs: [test_dodawanie, test_odejmowanie, test_mnozenie, test_dzielenie]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r ./Lab_7/env_415916/requirements.txt

      - name: Run new tests
        run: |
          cd ./Lab_7/env_415916 && pytest new_tests.py
