name: lab_8_415916_test

on:
  push:
    branches:
      - lab8

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install libs for testing
      run: |
        pip install pytest

    - name: Prepare environment
      run: |
        cd ./Lab_8/env_415916 && python -m pip install -r requirements.txt

    - name: Run unit tests
      run: |
        cd ./Lab_8/env_415916/main && pytest calculator_test.py

  function_test:
    runs-on: ubuntu-latest
    needs: unit_test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install libs for testing
      run: |
        pip install pytest

    - name: Prepare environment
      run: |
        cd ./Lab_8/env_415916 && python -m pip install -r requirements.txt

    - name: Run app
      run: |
        cd ./Lab_8/env_415916/main && nohup python app.py &

    - name: Wait for app
      run: sleep 10

    - name: Run functional tests
      run: |
        cd ./Lab_8/env_415916/main && pytest app_test.py

  deployment:
    runs-on: ubuntu-latest
    needs: function_test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_415916 }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./Lab_8/env_415916
        file: ./Lab_8/env_415916/dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/415916:latest
